# Generated by Django 5.2.8 on 2026-01-23 14:15

import gta_5_news_site_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_text', models.FilePathField(path=gta_5_news_site_app.models.news_text_path)),
                ('image', models.FilePathField(path=gta_5_news_site_app.models.images_path)),
                ('pub_date', models.DateField(max_length=20)),
                ('news_source', models.CharField(max_length=20)),
            ],
        ),
    ]
