# Generated by Django 5.2.8 on 2026-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gta_5_news_site_app', '0002_remove_news_image_remove_news_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=65656, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_text',
            field=models.TextField(default=111111111),
            preserve_default=False,
        ),
    ]
