# Generated by Django 5.2.8 on 2026-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gta_5_news_site_app', '0003_news_image_news_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_source',
            field=models.CharField(default='Eyefind', max_length=20),
        ),
    ]
