# Generated by Django 5.2.8 on 2026-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gta_5_news_site_app', '0004_alter_news_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('Нов', 'Новость'), ('Стат', 'Статья')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
