# Generated by Django 5.2.8 on 2026-05-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gta_5_news_site_app', '0005_news_news_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDoesNotExist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('pub_date', models.DateField(max_length=20)),
                ('news_source', models.CharField(default='Weazel News', max_length=20)),
                ('news_type', models.CharField(choices=[], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_source',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_type',
        ),
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
