# Generated by Django 5.2.8 on 2026-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gta_5_news_site_app', '0006_objectdoesnotexist_remove_news_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdoesnotexist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='objectdoesnotexist',
            name='news_source',
        ),
        migrations.RemoveField(
            model_name='objectdoesnotexist',
            name='news_text',
        ),
        migrations.RemoveField(
            model_name='objectdoesnotexist',
            name='news_title',
        ),
        migrations.RemoveField(
            model_name='objectdoesnotexist',
            name='news_type',
        ),
        migrations.RemoveField(
            model_name='objectdoesnotexist',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='news_source',
            field=models.CharField(default='Weazel News', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='news_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(blank=True, choices=[('hot_news', 'Горячие новости'), ('top_of_the_week', 'Топ недели'), ('recomendations', 'Рекомендуем'), ('news_of_the_day', 'Новость дня'), ('media', 'СМИ и развлечения'), ('food', 'Еда и напитки'), ('money', 'Деньги и услуги'), ('travel', 'Путешествия и транспорт'), ('fashion', 'Мода и здоровье')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
